services:
   service-cyber_community:
      image: vulebaolong/img-cyber_community:latest
      container_name: con-cyber_community
      ports:
         - 3070:3069
      env_file:
         - .env
      # environment:
      #    - DATABASE_URL=${DATABASE_URL}
      #    - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      #    - ACCESS_TOKEN_EXPIRES=${ACCESS_TOKEN_EXPIRES}
      #    - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      #    - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES}
      #    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      #    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      depends_on:
         - service-mysql
      command: ["npm", "run", "start"]

   service-mysql:
      image: mysql
      container_name: con-mysql
      ports:
         - 3307:3306
      environment:
         MYSQL_ROOT_PASSWORD: "1234"
